### ISSUE TITLE
ccweb 看起來不能使用了，需要更新一下程式內部的 URL

### ISSUE THREAD

**Issue by efficacy38** [jiazheng0609/NCNU-course-alert#12]
原先的 URL: https://ccweb.ncnu.edu.tw/student/aspmaker_course_opened_detail_viewlist.php 會被導到 https://ccweb6.ncnu.edu.tw/student/aspmaker_course_opened_detail_viewlist.php

**Comment by snsd0805** [comment]
#13 fixed this issue. Thanks!
