### ISSUE TITLE
抓了一段時間後有機會撞到 500 - 內部伺服器錯誤

### ISSUE THREAD

**Issue by jiazheng0609** [jiazheng0609/NCNU-course-alert#8]
連續抓了一段時間後似乎會因為 session 過期而有如下回應 (已用 Big5 decode)：
```
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=big5"/>\r\n<title>500 - 內部伺服器錯誤。</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:9px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>伺服器錯誤</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>500 - 內部伺服器錯誤。</h2>\r\n  <h3>您要尋找的資源有問題而無法顯示。</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'
```

我在 https://github.com/jiazheng0609/NCNU-course-alert/commit/5d57d1ede38b26f56f0b4df85b03098ee0e39e34
所提出的方法，是判斷拿到的資料大小比我們平常正常情況下拿到的小太多時，用一個全域變數當做 flag 促使程式流程改變，重新取得 session，但在 https://github.com/jiazheng0609/NCNU-course-alert/commit/c63c6ee16998250b42a4f1a26d9e777b780f8699 改連結時被刪掉了。

是否需要討論其他 error handling 方法？我是想到或許改用 HTTP status 來判斷。
還有當 response 出錯時，執行流程也要改變，要阻止他進入 parser，不然 BeautifulSoup 會丟 exception。
 @snsd0805 你有什麼想法？

**Comment by jiazheng0609** [comment]
阿我漏考慮了，現在已經是不需要一開始先用校務系統帳密 login 了，我們是拿那網址第一次就成功，但之後失敗的時候我們是要隔一段時間再拿拿看？

**Comment by snsd0805** [comment]
c63c6ee 刪掉是因為原本要先透過 GET 帶 參數的方式設定要索取的年度資料，接著才去取 csv，但後來索取當年度 csv 資料是不用多經過一次「設定年度」的過程就可以直接取得帶有資料的 csv 

後來想想，這個 500 error 應該不是 session 過期產生的，因為以前 session 過期還是會丟資料，不過是空的內容。可能要嘗試接到 500 error 就重新送 request

**Comment by snsd0805** [comment]
我先放個一版，放著測試看看會不會卡住

只有判斷 status code == 200，如果有 error 就繼續下一迴圈繼續送 request

**Comment by snsd0805** [comment]
測試大概 18 hr ，已經沒有因為 500 error 問題而卡住，所以我直接 merge 進 main branch
